asapdiscovery/asapdiscovery

- covid_moonshot_ml/DockedDataset.py
- covid_moonshot_ml/E3NNBind.py
- covid_moonshot_ml/SchNetBind.py
- covid_moonshot_ml/add_seqres.py
- covid_moonshot_ml/find_all_mcs.py
- covid_moonshot_ml/rank_enantiomers.py
- covid_moonshot_ml/run_docking.py
- covid_moonshot_ml/train_dd.py
- covid_moonshot_ml/utils.py
Add docstrings for all functions and improve some other documentation.
> Improve documentation

- covid_moonshot_ml/data/dataset.py
Modified internal structure of DockedDataset class to be able to store multiple conformations of the same docked Mpro:compound_id combination. External-facing API is unchanged.
> Allow duplicate Mpro:compound_id in DockedDataset class

- covid_moonshot_ml/data/dataset.py
- covid_moonshot_ml/datasets/moonshot.py
- covid_moonshot_ml/datasets/utils.py
- covid_moonshot_ml/docking/docking.py
- covid_moonshot_ml/utils.py
Move imports to be more local, to resolve #12.
> Moved imports to be more local.

- scripts/hallucinate_fragalysis.py
Use pure OpenEye for docking so we have more control over the POSIT options.
> Use openeye docking

- covid_moonshot_ml/docking/analysis.py
- notebook/analyze-mers-docking-with-api.ipynb
Made only a single commit to this new branch but i think i'll go ahead and merge so that we only have to rebase `hallucinate-fragalysis` as in #39
> minor pull request to get rid of a branch with only one commit

- covid_moonshot_ml/datasets/moonshot.py
- covid_moonshot_ml/datasets/utils.py
- scripts/cdd_to_schema.py
Updated the CDD parsing functions to calculate and store the variance in the pIC50 measurement.
Replicate of previous PR #11
>  Add pIC50 uncertainties in schema objects

- covid_moonshot_ml/datasets/utils.py
- covid_moonshot_ml/modeling.py
- scripts/hallucinate_fragalysis.py
Updated the function to build design units to be able to handle building both monomers and dimers. Updated the `hallucinate_fragalysis.py` script to automatically generate both. Resolves #34
> Add ability to build both monomer and dimer design units

- covid_moonshot_ml/datasets/utils.py
- scripts/hallucinate_fragalysis.py
- scripts/test-ligand-filter.py
> add ligand filtering

- covid_moonshot_ml/data/dataset.py
- covid_moonshot_ml/utils.py
- scripts/train.py
Add functionality to add SMILES and pIC50 label data to the DockedDataset class.
> Add SMILES to DockedDataset object

- asapdiscovery/ml/dataset.py
- asapdiscovery/ml/models/GAT.py
- asapdiscovery/ml/scripts/train.py
- asapdiscovery/ml/utils.py
Add a class for a new dataset class that groups multiple poses for the same compound together. Also migrate to using the [MTENN](https://github.com/choderalab/mtenn/) package (also under development).
> Add grouped dataset and migrate to using MTENN

- asapdiscovery/ml/scripts/train.py
Add the ability to pass model config information as a CLI arg in the `train` script.
> Add the ability to pass model config information as a CLI arg

- asapdiscovery/ml/scripts/sweep.py
Add WandB sweep capabilities for e3nn model.
> Add WandB sweep capabilities for e3nn model

- asapdiscovery/ml/scripts/sweep.py
Add functionality for specifying optimizer type and parameters as part of a WandB sweep.
> Add optimizer type to WandB sweep

- asapdiscovery/ml/scripts/sweep.py
- asapdiscovery/ml/utils.py
Fix bug in optimizer config in sweeps.
> Fix bug in optimizer config in sweeps

- asapdiscovery/data/utils.py
- asapdiscovery/docking/scripts/collate_results.py
- asapdiscovery/docking/scripts/hallucinate_fragalysis.py
- asapdiscovery/docking/scripts/mass_add_seqres.py
- asapdiscovery/docking/scripts/run_docking_oe.py
- asapdiscovery/ml/scripts/rank_enantiomers.py
- asapdiscovery/ml/scripts/train.py
- asapdiscovery/tests/test_asapdiscovery.py
Fixes #136 
An extension of #131 adds a method to check that files are present and adds a simple debug tag. I have added the check in a few obvious places where files are required. Let me know if there are others or the tags are wrong.
> Add checks for files being present in lists and globs 

- asapdiscovery-data/asapdiscovery/data/openeye.py
> Make lack of OE license fail nicely 

- asapdiscovery-data/asapdiscovery/data/openeye.py
- asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py
Fix the script for creating a docked pose from the protein crystal structure and docked ligand SDF file. Add the function for doing this combination to `asapdiscovery.data.openeye`.
> Fix combining crystallographic protein structure and docked ligand SDF file

- .github/workflows/CI.yaml
- README.md
- devtools/conda-envs/asapdiscovery.yaml
Adds current recommended install path for getting up and running with the package to the README.
Closes #164.
> Added recommended install instructions to README.md

- asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
- asapdiscovery-ml/asapdiscovery/ml/utils.py
Add CLI args to the training script to allow specifying the seed for shuffling the dataset. Also fix a bug in the splitting method that made it so the dataset wasn't getting shuffled.
> Improve dataset splitting

- README.md
- asapdiscovery-data/pyproject.toml
- asapdiscovery-dataviz/pyproject.toml
- asapdiscovery-docking/pyproject.toml
- asapdiscovery-ml/pyproject.toml
- asapdiscovery-modeling/pyproject.toml
- asapdiscovery-simulation/pyproject.toml
> Python 3.9, 3.10 official support

- asapdiscovery-docking/asapdiscovery/docking/modeling.py
Prevent `res_list` from being called before being defined. Resolves #205
> Fix issue 205

- asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_retro_docking.sh
> Reconcile run docking oe differences

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-data/asapdiscovery/data/testing/test_resources.py
- asapdiscovery-data/asapdiscovery/data/tests/test_testing_resources.py
Fixes #187. 
Adds infrastructure to pull down files for testing from a public AWS S3 bucket.
> Add data pull for testing

- asapdiscovery-docking/asapdiscovery/docking/analysis.py
- asapdiscovery-docking/asapdiscovery/docking/notebooks/20230425_analysis_fauxalysis_docking.ipynb
> Fauxalysis v2

- asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
- devtools/conda-envs/asapdiscovery.yaml
> fix asapdiscovery dgl versioning

- asapdiscovery-data/pyproject.toml
Single line change, I like this script and would like to have access to it via entry point.
> add split-sdf-to-pyproject-toml

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-docking/asapdiscovery/docking/tests/test_rmsd_calculation.py
Since we've added OpenEye license to CI, no reason to skip this now!
Please approve so that we can pull it in!
> unskip rmsd calculation test

- .github/workflows/CI.yaml
- .github/workflows/clean_cache.yaml
- asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
- devtools/conda-envs/asapdiscovery.yaml
Setup cache for micromamba and clean on merge.
Use `pytest-xdist` to run tests in parallel.
> Speed up tests

- asapdiscovery-data/asapdiscovery/data/schema.py
- asapdiscovery-modeling/asapdiscovery/modeling/scripts/create_prep_inputs.py
- asapdiscovery-modeling/asapdiscovery/modeling/scripts/prep_targets.py
- asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prep_scripts.py
Switch to using json instead of pickle
> Switch to json

- .github/workflows/CI.yaml
- asapdiscovery-data/asapdiscovery/data/tests/test_fragalysis.py
- asapdiscovery-data/asapdiscovery/data/tests/test_testing_resources.py
- asapdiscovery-data/pyproject.toml
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_placeholder.py
- asapdiscovery-dataviz/pyproject.toml
- asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_placeholder.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_rmsd_calculation.py
- asapdiscovery-docking/pyproject.toml
- asapdiscovery-ml/asapdiscovery/ml/inference/inference.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_weights.py
- asapdiscovery-ml/pyproject.toml
- asapdiscovery-modeling/pyproject.toml
- asapdiscovery-simulation/pyproject.toml
- pyproject.toml
> Fix code coverage

- asapdiscovery-ml/asapdiscovery/ml/inference/inference.py
Fixes #257 
Adds correct kwargs for schnet inference to be in right units.
> Add SchNet pIC50 output

- asapdiscovery-data/asapdiscovery/data/logging.py
- asapdiscovery-data/asapdiscovery/data/tests/test_logging.py
> Change Filelogger default level to WARNING

- asapdiscovery-data/asapdiscovery/data/openeye.py
Fixes #315 
- Allow openeye loading and saving functions to take str or Path
- Improve type hinting.
> Allow openeye loading and saving functions to take str or Path, and improve typing. 

- asapdiscovery-data/asapdiscovery/data/tests/test_moonshot.py
> add xfail for moonshot downloads

- asapdiscovery-data/asapdiscovery/data/openeye.py
- asapdiscovery-data/asapdiscovery/data/postera/manifold_data_tags.yaml
- asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py
- asapdiscovery-docking/asapdiscovery/docking/docking_data_validation.py
- asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
- asapdiscovery-simulation/asapdiscovery/simulation/szybki.py
Fixes #366 
Adds Szybki freeform restriction energy computation as an analysis class in `simulation.`
> Add szybki restriction analysis

- asapdiscovery-simulation/asapdiscovery/simulation/current_fec_worfklow/compute_ddGs.py
Fixes #394  
Tagging @ijpulidos
> Add in analysis script for FECs

- asapdiscovery-data/asapdiscovery/data/aws/cloudfront.py
- asapdiscovery-data/asapdiscovery/data/aws/s3.py
- asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py
- asapdiscovery-data/asapdiscovery/data/services_config.py
- asapdiscovery-data/asapdiscovery/data/tests/test_postera.py
- asapdiscovery-data/asapdiscovery/data/tests/test_services_config.py
- asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
Fixes #388  
Superseeds #400 which requires pydantic 2.0 +
> Adds in pydantic settings to easily make interfaces to services. v2

- .gitignore
- devtools/conda-envs/asapdiscovery.yaml
Pin pydantic version directly.
> Pin pydantic version

- .gitignore
- asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
> Redo of visualisation and adaptive PRs (396, 380)

- asapdiscovery-data/asapdiscovery/data/moonshot.py
- asapdiscovery-data/asapdiscovery/data/scripts/download_moonshot_data.py
- asapdiscovery-data/asapdiscovery/data/tests/test_moonshot.py
- asapdiscovery-data/asapdiscovery/data/utils.py
Add functionality for downloading/parsing Mac1 data from CDD.
> Add functionality for downloading/parsing Mac1 data from CDD

- asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
> Fix use of viz_target rather than target in e2e

- asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> Return none from ML models if nothing available for a given target.

- asapdiscovery-data/asapdiscovery/data/postera/postera_factory.py
Fixes #446
Makes a factory that can create Ligand Schema from postera molecule sets. Queried with the Postera people how the VCIDs appear in the API if at all.
> Add postera factory to make ligands. 

- asapdiscovery-modeling/asapdiscovery/modeling/modeling.py
> Fix single target

- asapdiscovery-data/asapdiscovery/data/schema_v2/fragalysis.py
- asapdiscovery-data/asapdiscovery/data/schema_v2/molfile.py
- asapdiscovery-data/asapdiscovery/data/tests/test_molfile_factory_schema_v2.py
- asapdiscovery-data/asapdiscovery/data/tests/test_molfile_schema_v2.py
> Add factory for reading from generic molecule file. 

- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_fec_schema.py
> Add check during creation of FEC dataset that there are no duplicate ligands

- asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
Fixes #496 
Should fix broken end2end wf and also failing docking CI.
> Add check for single binding site in PLIP interactions

- asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
fixes https://github.com/choderalab/asapdiscovery/issues/478
ez pz, this doesn't break anything.
> swap to using high-level gifsicle api

- .github/workflows/docking.yaml
Add some swap space to docking action run
> Try add swap space to docking

- asapdiscovery-docking/asapdiscovery/docking/docking.py
- asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
Fixes #519 
Branches off of #518
> Add openmm platform selection in `VanillaMDSimulator` and e2e workflow.

- asapdiscovery-data/asapdiscovery/data/openeye.py
- asapdiscovery-data/asapdiscovery/data/schema_v2/identifiers.py
- asapdiscovery-data/asapdiscovery/data/schema_v2/ligand.py
- asapdiscovery-data/asapdiscovery/data/schema_v2/target.py
- asapdiscovery-data/asapdiscovery/data/tests/test_ligand_schema_v2.py
This PR supersedes #531 as I messed up updating the main branch. 
> Ligand SDF round trip v2

- asapdiscovery-data/asapdiscovery/data/postera/manifold_artifacts.py
> Fix MD upload for simulations that are not attempted.

- asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
- asapdiscovery-simulation/asapdiscovery/simulation/szybki.py
Quick fix to change the case when setting the level of logging in some cases.
> Fix case in `setLevel` for logging

- asapdiscovery-data/asapdiscovery/data/fitness.py
we weren't parsing the fitness JSON correctly for Sars2 Mpro.
> add proper sars2 mpro fitness parse

- .gitignore
- .readthedocs.yaml
- asapdiscovery-alchemy/asapdiscovery/alchemy/__init__.py
- asapdiscovery-modeling/asapdiscovery/modeling/__init__.py
- asapdiscovery-simulation/asapdiscovery/simulation/__init__.py
- docs/README.md
- docs/_templates/custom-class-template.rst
- docs/_templates/custom-module-template.rst
- docs/api.rst
- docs/conf.py
- docs/getting_started.rst
- docs/index.rst
- docs/requirements.yaml
- readthedocs.yml
> Make docs and RTD docs build

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-docking/asapdiscovery/docking/cli.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
> initial dask tuning for large-scale docking 

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
Adds ability use dask-workers on CPUqueue using suggested fix from MSK HPC.
> Try and fix dask CPU workers

- README.md
I was completely unable to build the repo with conda, so I think we should make that clear in the main readme.
> add mamba requirement to main readme

- asapdiscovery-data/asapdiscovery/data/postera/postera_uploader.py
> Fix overwrite on postera molecule set

- asapdiscovery-docking/asapdiscovery/docking/cli.py
- asapdiscovery-docking/asapdiscovery/docking/docking_v2.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
Fixes #584 
@JenkeScheen 
@apayne97  importantly changes the default to not do oeomega enumeration for each compound before docking in large scale workflow
> Improve docking efficiency

- asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py
Add response printing from postera on error
> Add response printing from postera on error

- asapdiscovery-data/asapdiscovery/data/schema_v2/schema_base.py
Fixes #619 
Thanks @apayne97 for spotting.
> Fix `eq` bug in `schema_base`

- asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/workflows.py
> Change large scale workflow to subclass `DockingWorkflowBase`

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-data/asapdiscovery/data/enum.py
- asapdiscovery-data/asapdiscovery/data/postera/manifold_data_validation.py
- asapdiscovery-ml/asapdiscovery/ml/models.py
- asapdiscovery-modeling/asapdiscovery/modeling/protein_prep_v2.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
> Replace repeated use of enum with get_values method with baseclass

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
> Fix file hash on test file 

- asapdiscovery-docking/asapdiscovery/docking/cli.py
- asapdiscovery-docking/asapdiscovery/docking/openeye.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
Fixes #666 
Also adds no-omega option to small scale docking.
> Fix artifact column issues for fitness

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
- asapdiscovery-modeling/asapdiscovery/modeling/workflows/protein_prep.py
> Re-add dask CFG after being removed on main. 

- asapdiscovery-data/asapdiscovery/data/postera/manifold_artifacts.py
- asapdiscovery-data/asapdiscovery/data/postera/manifold_data_validation.py
- asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
Reverts the changes made for postera bleaching that has now been resolved upstream. 
Fixes #629
> [WIP, testing] revert postera bleaching issues

- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
> Pin to python sub 3.11

- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
Move `mtenn` dep from GitHub install to `conda-forge`.
> Update mtenn dep

- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
Perhaps @jthorton knows whether there was some versioning issue?
> Test cinnabar from conda-forge

- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
This PR changes the results gathering to use the process pool API point which gathers all transformation results for a given network and should speed up the action. 
> Faster results gathering from Alchemiscale

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
> Fix passing of silence_logs

- asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
> Fix non-supression of hydrogens

- asapdiscovery-data/asapdiscovery/data/tests/test_cdd_download.py
> Xfail CDD download tests

- asapdiscovery-cli/asapdiscovery/cli/cli_args.py
- asapdiscovery-data/asapdiscovery/data/tests/test_cdd_download.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/gif_viz.py
- asapdiscovery-docking/asapdiscovery/docking/cli.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
> Fix v2 imports and naming for `simulation` submodule

- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
> Fix cudatoolkit pin

- asapdiscovery-ml/asapdiscovery/ml/schema_v2/trainer.py
Added different target_prop support in ml trainer.py. Very straightforward changes.
> Added different target_prop support in asapdiscovery-ml trainer.py

- .github/workflows/alchemy.yaml
- .github/workflows/data.yaml
- .github/workflows/dataviz.yaml
- .github/workflows/docking.yaml
- .github/workflows/macos-ci.yaml
- .github/workflows/ml.yaml
- .github/workflows/modeling.yaml
- .github/workflows/simulation.yaml
> Add merge group to runners

- asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
> Fix propogation of timing info to GIFVisualizer

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_gif_viz.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_html_viz.py
> Fix HTML OEMol codepath used in argos

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-data/asapdiscovery/data/tests/test_dask_clusters.py
> Fix issues around passing of loglevels in dask code and improve testing

- asapdiscovery-data/asapdiscovery/data/postera/manifold_data_tags.yaml
- asapdiscovery-data/asapdiscovery/data/schema_v2/meta_ligand_factory.py
- asapdiscovery-docking/asapdiscovery/docking/docking_data_validation.py
- asapdiscovery-docking/asapdiscovery/docking/scorer.py
> E3nn scorer alias

- .github/workflows/deploy_docker.yaml
- devtools/containers/Dockerfile
A ready to go docker env 
Fixes #856 
Fixes #699
> Make a container deployment

- devtools/containers/Dockerfile
> Tiny dockerfile fix

- devtools/containers/Dockerfile
> Fix dockerfile

- asapdiscovery-docking/asapdiscovery/docking/tests/test_scorers.py
> Add tests for FINTScorer

- docs/requirements.yaml
> Try and fix RTD

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/conftest.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_gif_viz_v2.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_html_viz_v2.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/gif_viz.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/html_viz.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/visualizer.py
- asapdiscovery-docking/asapdiscovery/docking/docking.py
- asapdiscovery-docking/asapdiscovery/docking/openeye.py
- asapdiscovery-docking/asapdiscovery/docking/scorer.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
> Remove repetition in dask backends to a decorator, smooth out API and add tests

- asapdiscovery-data/asapdiscovery/data/dask_utils.py
> Fix none being returned by vmap

- asapdiscovery-data/asapdiscovery/data/postera/manifold_artifacts.py
> Fix edge case in manifold uploader where there are no artifacts

- asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/gif_viz.py
- asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
> Add SMILES deduplication to `small-scale`

- asapdiscovery-docking/asapdiscovery/docking/scorer.py
> Register ML scorer classes

- asapdiscovery-data/asapdiscovery/data/services/postera/molecule_set.py
- asapdiscovery-data/asapdiscovery/data/tests/postera/test_postera_live.py
> try fix for changed API backend

- asapdiscovery-ml/asapdiscovery/ml/cli_args.py
- asapdiscovery-ml/asapdiscovery/ml/config.py
- asapdiscovery-ml/asapdiscovery/ml/es.py
- asapdiscovery-ml/asapdiscovery/ml/trainer.py
Implement new early stopping method (`patient_converged`) that checks for convergence and then continues with the training loop to ensure that the model has actually converged and not just reached a local minimum.
> Implement PatientConvergedEarlyStopping.

- asapdiscovery-genetics/asapdiscovery/genetics/blast.py
- asapdiscovery-genetics/asapdiscovery/genetics/scripts/make_alignment.py
- asapdiscovery-genetics/asapdiscovery/genetics/seq_alignment.py
- asapdiscovery-genetics/pyproject.toml
Adding modules for the asapdiscovery-genetics repo,  including blast search, sequence alignment and structure alignment code. Code needs revision before approval. 
> Code for the asap-genetics repo

- asapdiscovery-ml/asapdiscovery/ml/trainer.py
Add handling of `extra_config` in `Trainer` so that a list of key:value pair strings can be passed from the CLI. Closes #753.
> Add handling of extra_config option in Trainer

- asapdiscovery-cli/asapdiscovery/cli/cli.py
- asapdiscovery-ml/asapdiscovery/ml/cli.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_ml_cli.py
- asapdiscovery-ml/pyproject.toml
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py
> Connect up ML cli to mega cli

- asapdiscovery-ml/asapdiscovery/ml/trainer.py
Realized that I left out a scaling term in the loss when using batches.
> Fix batch training math

- asapdiscovery-data/asapdiscovery/data/scripts/split_fragment_screen.py
> `data` Quality of Life improvements to split_fragment_screen.py

- asapdiscovery-data/asapdiscovery/data/scripts/download_cdd_data.py
- asapdiscovery-data/asapdiscovery/data/services/cdd/cdd_download.py
> Fix missed import reference updates in asapdiscovery-data.

- asapdiscovery-data/asapdiscovery/data/services/postera/postera_uploader.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
> Stopgap for no UUID in postera artifact upload

- asapdiscovery-genetics/asapdiscovery/genetics/blast.py
- asapdiscovery-genetics/asapdiscovery/genetics/calculate_rmsd.py
- asapdiscovery-genetics/asapdiscovery/genetics/scripts/make_alignment.py
- asapdiscovery-genetics/asapdiscovery/genetics/scripts/structure_alignment.py
- asapdiscovery-genetics/asapdiscovery/genetics/seq_alignment.py
- asapdiscovery-genetics/pyproject.toml
Adding code for structure alignment following the sequence alignment pipeline. Process is described in HOWTO Notion page https://www.notion.so/asapdiscovery/HOWTO-Run-a-sequence-alignment-job-ae1bf71d092b44a9acfc3064362c3b99?pvs=4 
> Struct alignment code

- asapdiscovery-alchemy/pyproject.toml
- asapdiscovery-cli/pyproject.toml
- asapdiscovery-data/pyproject.toml
- asapdiscovery-dataviz/pyproject.toml
- asapdiscovery-docking/pyproject.toml
- asapdiscovery-genetics/pyproject.toml
- asapdiscovery-ml/pyproject.toml
- asapdiscovery-modeling/pyproject.toml
- asapdiscovery-simulation/pyproject.toml
- asapdiscovery-workflows/pyproject.toml
> Fix `pyproj.toml` VCS behaviour 

- asapdiscovery-alchemy/pyproject.toml
- asapdiscovery-cli/pyproject.toml
- asapdiscovery-data/pyproject.toml
- asapdiscovery-dataviz/pyproject.toml
- asapdiscovery-docking/pyproject.toml
- asapdiscovery-genetics/pyproject.toml
- asapdiscovery-ml/pyproject.toml
- asapdiscovery-modeling/pyproject.toml
- asapdiscovery-simulation/pyproject.toml
- asapdiscovery-workflows/pyproject.toml
> Fix python pin in `docking`

- asapdiscovery-ml/asapdiscovery/ml/cli.py
- asapdiscovery-ml/asapdiscovery/ml/cli_args.py
- asapdiscovery-ml/asapdiscovery/ml/config.py
- asapdiscovery-ml/asapdiscovery/ml/es.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_es.py
- asapdiscovery-ml/asapdiscovery/ml/trainer.py
Add some functionality to the `EarlyStopping` classes to make sure a model is trained for some minimum number of epochs before stopping training. Also some tests to make sure they're all functioning as expected.
> Add burn-in parameter for early stopping

- asapdiscovery-workflows/pyproject.toml
> Fix workflows pyproject.toml

- asapdiscovery-data/asapdiscovery/data/services/postera/__init__.py
> Add `__init__.py` files

- asapdiscovery-ml/asapdiscovery/ml/models.py
> Add Model query on target model availability

- asapdiscovery-ml/asapdiscovery/ml/cli_args.py
- asapdiscovery-ml/asapdiscovery/ml/cli_sweep.py
- asapdiscovery-ml/asapdiscovery/ml/config.py
- asapdiscovery-ml/asapdiscovery/ml/sweep.py
We updated the way the training CLI handles combining config caches and CLI args, but never updated the sweep CLI in the same way. This PR addresses that and makes sure the sweep CLI reconciles everything in a sensible manner.
> Rework sweep CLI logic

- asapdiscovery-docking/asapdiscovery/docking/docking.py
- asapdiscovery-docking/asapdiscovery/docking/openeye.py
- docs/tutorials/index.rst
- examples/docking_and_scoring.ipynb
- examples/protein_and_ligand_prep.ipynb
> Add docking and scoring documentation

- .gitignore
- examples/running_md_simulations.ipynb
> Add tutorial for running MD simulations

- docs/guides/developing_asapdiscovery.md
- docs/guides/index.md
- docs/guides/using_asapdiscovery.md
- docs/guides/using_docking_cli.md
- docs/index.md
- docs/requirements.yaml
- examples/running_alchemical_free_energy_calculations.ipynb
- examples/running_md_simulations.ipynb
- examples/tutorial_files/running_md_simulations/visualise_docked.html
- examples/visualizing_asap_targets.ipynb
> Doc tweaks

- asapdiscovery-data/asapdiscovery/data/services/postera/manifold_artifacts.py
- asapdiscovery-data/asapdiscovery/data/services/postera/postera_uploader.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
> Fix gif alignment

- asapdiscovery-data/asapdiscovery/data/services/postera/manifold_artifacts.py
- asapdiscovery-data/asapdiscovery/data/services/postera/postera_uploader.py
- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
- asapdiscovery-simulation/asapdiscovery/simulation/tests/test_simulate.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
> Fix simulator serialization

- asapdiscovery-cli/asapdiscovery/cli/cli_args.py
- asapdiscovery-data/asapdiscovery/data/metadata/resources.py
- asapdiscovery-data/asapdiscovery/data/operators/selectors/mcs_selector.py
- asapdiscovery-data/asapdiscovery/data/schema/complex.py
- asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
- asapdiscovery-modeling/asapdiscovery/modeling/modeling.py
- asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/workflows.py
- asapdiscovery-workflows/asapdiscovery/workflows/prep_workflows/cli.py
> Add chain flexibility to CLI and automatic chain selection to target specs

- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
> Add explicit stop for  no  simulations run

- .github/workflows/workflows.yaml
> Attempt to fix workflows CI

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-workflows/asapdiscovery/workflows/tests/prep_cli/test_prep_cli.py
> Test prep cli for each target in workflows

- devtools/conda-envs/asapdiscovery-macOS-12.yml
- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
> Pin DGL version to <= 2.0.0

- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/prep_workflow.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_alchemy_prep.py
fixes https://github.com/asapdiscovery/asapdiscovery/issues/1099
> log smiles of injected compounds

- asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
- asapdiscovery-docking/asapdiscovery/docking/openeye.py
Fixes #1097 
Wrong attribute was messing up dataframe linking.
> Fix docking issues

- asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
Add tests to cover missed CLI commands.
> `ASAP-Alchemy`: Testing CLI

- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-ml/asapdiscovery/ml/asap_models.yaml
- asapdiscovery-ml/asapdiscovery/ml/tests/test_weights.yaml
> Fix up base paths  for S3 to cloudfront distro

- asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/predict.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
> Fix failing attempt to calculate bootstraps where only a single EXP prediction is available V2

- asapdiscovery-data/asapdiscovery/data/schema/ligand.py
> HOTFIX: Fix tag non hashable

- asapdiscovery-data/asapdiscovery/data/operators/selectors/mcs_selector.py
- asapdiscovery-data/asapdiscovery/data/tests/test_selectors.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/symexp_crystal_packing.py
Fixes #1157 with a better scaling algorithm and parallelism
> Add RascalMCES selector and switch workflows to using it

- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
> Fix typing Simulate.py

- asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py
> Add failure tolerance in ligand creation from PosteraFactory

- asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py
Makes printing progress optional in `pull-all`
> make progress optional

- asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py
> Forgot to let black apply

- asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/ligand_transfer_docking.py
Fixes #1153 
I think we could already do this so I added implementation @mariacm12
> Add outpaths to lig transfer docking

- asapdiscovery-ml/asapdiscovery/ml/inference.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py
> Fix bad cast in inference code V2

- asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/scripts/generate_test_files.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_fec_schema.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- devtools/conda-envs/asapdiscovery-macOS-12.yml
- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
> [DNM] OpenFE 1.0 + Alchemiscale 0.5 compat

- asapdiscovery-ml/asapdiscovery/ml/inference.py
> Fix array cast error properly for Numpy >= 1.26

- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/conftest.py
> Fix duplicated test fixture

- asapdiscovery-cli/asapdiscovery/cli/cli_args.py
- asapdiscovery-data/asapdiscovery/data/services/postera/manifold_data_tags.yaml
- asapdiscovery-docking/asapdiscovery/docking/docking_data_validation.py
- asapdiscovery-docking/asapdiscovery/docking/scorer.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_scorers.py
- asapdiscovery-ml/asapdiscovery/ml/models.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
> HOTFIX: Ml prediction in docking workflows. 

- asapdiscovery-ml/asapdiscovery/ml/models.py
- asapdiscovery-ml/asapdiscovery/ml/tests/test_models.py
Bugfix for Ml registry + tests
> Add tests and bugfix for registry

- .github/workflows/alchemy.yaml
- .github/workflows/cli.yaml
- .github/workflows/data.yaml
- .github/workflows/dataviz.yaml
- .github/workflows/docking.yaml
- .github/workflows/genetics.yaml
- .github/workflows/macos-ci.yaml
- .github/workflows/ml.yaml
- .github/workflows/modeling.yaml
- .github/workflows/simulation.yaml
- .github/workflows/workflows.yaml
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
> Pin micromamba

- devtools/conda-envs/asapdiscovery-macOS-12.yml
- devtools/conda-envs/asapdiscovery-macOS-latest.yml
- devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
Migration to new `alchemiscale` and `openfe` versions
> Alchemiscale 0.5.1

- asapdiscovery-data/asapdiscovery/data/cli/cli.py
Hook the CDD downloading into the main CLI.
> Add CDD download to CLI

- asapdiscovery-data/asapdiscovery/data/services/cdd/cdd_download.py
- asapdiscovery-data/asapdiscovery/data/util/utils.py
- asapdiscovery-ml/asapdiscovery/ml/cli_mlops.py
Add filter on fluorescence experimental errors to prevent overly large errors from rounding the readout values to 0/10. Closes #1234.
> Add filter on fluorescence experimental errors

- asapdiscovery-data/asapdiscovery/data/tests/test_fragalysis.py
Skip fragalysis tests until fragalysis is back up.
> xfail fragalysis again

- asapdiscovery-data/asapdiscovery/data/cli/cli.py
- asapdiscovery-docking/asapdiscovery/docking/openeye.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/ligand_transfer_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
- asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/symexp_crystal_packing.py
Improve the number of poses generated.
> Add last ditch docking with fred and fiddle with docking options

- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/charge.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/prep_workflow.py
- asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py
fixes https://github.com/asapdiscovery/asapdiscovery/issues/1202
> add progress bar to `alchemy` docking (`prep run`)

- README.md
> Fix trailing whitespace

- asapdiscovery-alchemy/asapdiscovery/alchemy/cli/prep.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/charge.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/schema/prep_workflow.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
- asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
- asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py
deals with edge-cases during docking, ultimately letting them fail.
> [WIP] Alchemy docking deal with edgecases

- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
- asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
- asapdiscovery-docking/asapdiscovery/docking/tests/test_pose_generation.py
> Fix CI again

- asapdiscovery-alchemy/asapdiscovery/alchemy/interfaces.py
to connect to the new asap alchemiscale instance
> Update ALCHEMISCALE_URL to new endpoint
