covid_moonshot_ml/datasets/utils.py, scripts/hallucinate_fragalysis.py, scripts/test-ligand-filter.py
* create script to test implementation of ligand filtering
* use dictionary instead of list for ligand filtering function
* implement filtering a dictionary of CrystalCompoundData
* implement filtering code within the hallucinate_fragalysis.py script
* turn smarts_queries csv file into an input argument
* Fix typo.
* Rework logic for filtering compounds using new functions.
* Remove default argument for `--smarts_queries` to avoid accidental filtering.
* Update comment.
Co-authored-by: kaminow <benjamin.kaminow@choderalab.org>
=> add ligand filtering (#56)

asapdiscovery/docking/docking.py, asapdiscovery/docking/scripts/run_docking_oe.py
Implements SMILES entries into docking outputs as previously done by @kaminow, I think this was lost during the recent refactor. Having SMILES is very helpful downstream during processing of docking results.
=> Add smiles docking output

asapdiscovery/docking/modeling.py, asapdiscovery/docking/scripts/prep_proteins.py, cluster_scripts/prep_full_mpro.sh
We've had a hard time tracking down when OpenEye grabs the ligand from chain A vs chain B to use to create the receptor grid. In order to do this explicitly, @kaminow has written a function to first remove the ligand from the chain we don't need.
=> Remove extra ligands

asapdiscovery/docking/scripts/run_docking_oe.py
While running `run_docking_oe.py` with the CLI flag `-r` there are currently no tests to check whether the user has correctly pointed to the folder with prepped receptors. This quick check informs the user in case `glob` finds no paths to receptor files.
This is a useful check because in the current state of the code an error is thrown *way* [downstream](https://github.com/choderalab/covid-moonshot-ml/blob/main/asapdiscovery/docking/scripts/run_docking_oe.py#L391) and it takes a while to trace back the error manually. 
=> add quick test to check if user has correctly pointed to prepped structures

asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py, asapdiscovery-data/asapdiscovery/data/tests/test_postera.py
We shouldn't shadow `list` or any python keywords. This changes the `list` method from `MoleculeSetAPI` to `list_available`.
Resolves #156
=> Avoiding shadowing python list keyword with method

asapdiscovery-data/asapdiscovery/data/openeye.py, asapdiscovery-data/asapdiscovery/data/utils.py, asapdiscovery-docking/asapdiscovery/docking/analysis.py, asapdiscovery-docking/asapdiscovery/docking/docking.py, asapdiscovery-docking/asapdiscovery/docking/mcs.py, asapdiscovery-docking/asapdiscovery/docking/modeling.py, asapdiscovery-docking/asapdiscovery/docking/scripts/build_design_units.py, asapdiscovery-docking/asapdiscovery/docking/scripts/fauxalysis_from_docking.py, asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py, asapdiscovery-docking/asapdiscovery/docking/scripts/prep_fragalysis_dus.py, asapdiscovery-docking/asapdiscovery/docking/scripts/prep_proteins.py, asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py, asapdiscovery-docking/asapdiscovery/docking/scripts/score_structures.py, asapdiscovery-docking/asapdiscovery/docking/scripts/test-protein-prep.py
Fixes #155 
Moves all openeye imports to be namespaced under our openeye wrapper so that the license can be checked at import time. 
Tagging @apayne97, @kaminow @ijpulidos @dotsdl @mikemhenry so that y'all are aware that this is how OE stuff should be imported from now on.
```python
from asapdiscovery.data.openeye import oefoo, oebar
```
=> Change OE imports to be namespaced under `asapdiscovery` for license check. 

asapdiscovery/ml/__init__.py, asapdiscovery/ml/es.py, asapdiscovery/ml/scripts/train.py, asapdiscovery/ml/utils.py
Implement early stopping when training a model. Stops training when `val_loss` is no longer increasing. Also, `train.py` now saves the final model weights as `final.th`.
=> Add early stopping

asapdiscovery/ml/utils.py
Single commit that matches the tensor shape of the model prediction to the shape of the target value in order to avoid the broadcasting warnings from `torch`.
=> Reshape model predictions to match target.

asapdiscovery/ml/loss/MSELoss.py, asapdiscovery/ml/models/GAT.py, asapdiscovery/ml/utils.py
Improve the GAT model by using a 2 layer MLP with ReLU activation instead of the single linear layer previously being used. This makes things more in line with the [GATPredictor](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/model/model_zoo/gat_predictor.py) class from `dgl-lifesci`.
Also adjusted the MSELoss class to make sure that averages are calculated correctly when there are multiple predictions.
=> Improve GAT model

asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py, asapdiscovery-ml/asapdiscovery/ml/models.yaml, asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py, asapdiscovery-ml/asapdiscovery/ml/tests/test_weights.yaml, devtools/conda-envs/asapdiscovery.yaml
Add new GAT weights that are compatible with the new version of `dgl`. Closes #260.
=> Fix issue 260

asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py, asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
Fixes #393 
Adds in `keepIds=True` so the right residue numbers are written to PDB files.
=> Fix for GIF viz so that pocket is coloured correctly

asapdiscovery-ml/asapdiscovery/ml/scripts/plot_data_efficiency.py, asapdiscovery-ml/asapdiscovery/ml/scripts/train.py, asapdiscovery-ml/asapdiscovery/ml/utils.py
Redo of #406, should have all suggestions there addressed.
Change the stats that are tracked logged during training to include the compound and label associated with loss values, rather than just the loss values themselves. This will make it easier to figure out what's going on in training and isolate any specific molecules that might be difficult for the model.
Also some other minor changes that coincided with this, mainly a rearrangement of the code in train.py to be smarter about wandb initialization and letting it play better with CLI args.
=> Improve loss tracking

asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
Previously we were logging SMILES and molecular structures to WandB during training runs, which might be an issue when/if we start working with P5 data. I also added logging for a couple other experimental values.
=> Don't log (potentially) confidential info

asapdiscovery-data/asapdiscovery/data/schema_v2/target.py, asapdiscovery-data/asapdiscovery/data/tests/test_target_schema_v2.py
Fixes #434
Target schema built directly from a PDB should exclude the ligand, instead this is handled by a `Ligand` and combined in a Complex
=> Make targets build from PDB strictly protein only.

asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_fec_schema.py, asapdiscovery-data/asapdiscovery/data/schema_v2/ligand.py
Update `Ligand` `__eq__` method to exclude SDF header lines. Should fix #463
=> Fix Ligand equality checking

.github/workflows/alchemy.yaml, .github/workflows/data.yaml, .github/workflows/dataviz.yaml, .github/workflows/docking.yaml, .github/workflows/macos-ci.yaml, .github/workflows/ml.yaml, .github/workflows/modeling.yaml, .github/workflows/simulation.yaml
Testing if separating workflows for packages fixes our CI.
In this case it is testing `macos` in a single workflow for all subpackages. This is possible since the "offending" tests were skipped for this OS.
On the other hand, we are separating all subpackages tests for `linux`. It is going to be a bit annoying when we need to update them, but I think it's better to have a single approach (everything separated and "flexible") than having to think what is separated and what isn't. We would need to study if we hit a limit with the amount of workflows or workers that we can run in the project but I think we are fine that way as far as I have tested.
Resolves #265 
Resolves #480
=> Separate workflows/CI for subpackages

asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
Adjust interaction depiction in the case of a `fitness` HTML viz. Here we're going to color interactions by fitness (of the residue it hits) instead of by interaction type (which can be inferred easily anyway). This will enable the viewer to quickly see if a posed compound is interacting with mutable residues or not. New depiction with interactions colored by fitness:
We're adding:
- color interactions the same way as residues (white=no fit mutants, all the way to deep red which = many fit mutants)
- color interactions green if they hit the protein backbone (this is a good tactic and should be encouraged by highlighting it a separate color)
One issue is that light-red and white are difficult to distinguish. This also applies to residue surface coloring, so should be handled in a separate …
=> Add fitness interactions

asapdiscovery-docking/asapdiscovery/docking/docking.py
A re-occurence of https://github.com/openforcefield/openff-toolkit/issues/1615 is interfering in openmm making systems when Omega is being called, under the hood, removing the openeye logging manipulation fixes it. This is despite the initial fix detailed in the issue :(
=> Remove OE logging in docking

asapdiscovery-docking/asapdiscovery/docking/docking.py, asapdiscovery-ml/asapdiscovery/ml/inference/inference.py, asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py
Add ability to run inference directly on OEMol for the `StructuralInference` class. Once the new docking stuff is merged we can also add a method to predict from `DockingResult` object if we want. Closes #253
=> Add ability to run inference directly on OEMol

asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml, asapdiscovery-data/asapdiscovery/data/utils.py
Changes filtering molecules that were downloaded from CDD so that data being semi-quantitative is no longer a criteria for inclusion, but only for exclusion if `retain_semiquantitative_data == False`. Fixes #539.
=> Adjust molecule filtering to make more sense

.gitignore
Adds chemical file formats to gitignore.
initial partial fix of #538
=> add chemical file formats  to gitignore

asapdiscovery-alchemy/pyproject.toml, asapdiscovery-data/pyproject.toml, asapdiscovery-dataviz/pyproject.toml, asapdiscovery-docking/pyproject.toml, asapdiscovery-ml/pyproject.toml, asapdiscovery-modeling/pyproject.toml, devtools/conda-envs/asapdiscovery-macOS-latest.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
Fixes #548
Makes pyproject.tomls for subprojects empty, meaning you should use the carefully managed conda env to install everything. 
We can re-populate when things are more settled for subpackages if we like.
=> Make pyproj.tomls to not install anything

asapdiscovery-docking/asapdiscovery/docking/scorer_v2.py, asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
For new targets without ML models, we need to gracefully handle no available models in new scorer API
=> Fix scorer jamming when no model available for a given target

asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
It's embarassing to get an error within the error messaging
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/paynea/miniconda3/envs/ad-3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
msg = self.format(record)
File "/home/paynea/miniconda3/envs/ad-3.9/lib/python3.9/logging/__init__.py", line 927, in format
return fmt.format(record)
File "/home/paynea/miniconda3/envs/ad-3.9/lib/python3.9/logging/__init__.py", line 663, in format
record.message = record.getMessage()
File "/home/paynea/miniconda3/envs/ad-3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File …
```
=> Fix logging error in run_openeye_oe

asapdiscovery-data/asapdiscovery/data/utils.py
Closes #173 
Redundant since `docking.analysis.calculate_rmsd_openeye` works and is what we're using already
=> delete old rmsd calculation functions

asapdiscovery-data/asapdiscovery/data/fitness.py, asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/pose_to_viz.py
quick PR that satisfies a requirement for https://github.com/choderalab/asapdiscovery/issues/566, now have a CLI endpoint to generate either a subpocket or fitness HTML starting from a PDB file and an SDF.
=> add fitness option to `pose-to-viz.py`

asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml, asapdiscovery-modeling/asapdiscovery/modeling/protein_prep_v2.py, asapdiscovery-modeling/asapdiscovery/modeling/tests/test_protein_prep_v2.py
This PR fixes an issue where the loop db file path is set to `str(None)` when not supplied by mistake causing a fatal error with openeye. 
=> Fix protein prep loop db filepath 

asapdiscovery-data/asapdiscovery/data/postera/manifold_data_validation.py, asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
Adds pre-bleaching of column names to the postera convention ("_" not "-")  when uploading to postera, so that data can be joined to existing columns, meaning we don't have to erase all pre-existing custom data. See #629 and #628 for more info. 
**THIS SHOULD BE REVERTED ONCE UPSTREAM #628 IS IMPLEMENTED**
=> Add column pre-bleaching for postera

.github/PULL_REQUEST_TEMPLATE.md
Fixes #176 
Adds developer certificate of origin so that contributors can affirm that they contribute under the LICENSE.  This is the least invasive way to go, and we should probably have this in place is my understanding. I will wait for confirmation from @jchodera 
=> Add Developer Certificate of Origin

asapdiscovery-data/asapdiscovery/data/postera/manifold_data_validation.py, asapdiscovery-data/asapdiscovery/data/postera/postera_uploader.py
Partial fix of #643 
When molecule sets were being uploaded to postera, we were forbidding upload and instead making new ones, this allows old and new molecule sets to be joined with the `PosteraUploader`
=> Fixes ability of PosteraUploader to append to an existing MoleculeSet, 

asapdiscovery-ml/asapdiscovery/ml/asap_models.yaml, asapdiscovery-ml/asapdiscovery/ml/tests/test_models.py
Add new SchNet model trained with a lower learning rate to avoid the weights collapsing. These models were trained using `mtenn v0.4.0`, so probably shouldn't be used with previous versions. This is the version that's pinned in the `asapdiscovery` conda env files, so it shouldn't cause any issues.
=> Add new models trained with better learning rate

asapdiscovery-data/asapdiscovery/data/dask_utils.py, asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml, asapdiscovery-docking/asapdiscovery/docking/cli.py, asapdiscovery-docking/asapdiscovery/docking/tests/cli/test_docking_cli.py, asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py, asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
Fixes #665 
Adds ability to run in a local-gpu dask mode, currently some issues around distributed and `dask_cuda` version pins meaning we are going to have to wait a bit to re-enable log forwarding.
=> Adds local GPU dask client override for local dask mode in small-scale docking

asapdiscovery-dataviz/asapdiscovery/dataviz/viz_v2/gif_viz.py
Fixes two issues:
- ligand was not being aligned together with the protein, so was placed way outside of pocket by GIF viz. 
-> done by jumping alignment step to just after loading trajectory instead of after application of centering etc
- hotfix for https://github.com/choderalab/asapdiscovery/issues/671, still need to make a more modular solution.
-> done by adding a default value of `start` based on the default MD protocol
=> fix alignment and long GIF

asapdiscovery-docking/asapdiscovery/docking/openeye.py
Adds back the functionality from 
https://github.com/choderalab/asapdiscovery/blob/f83d4d206dcb96fbeca385b7f17b817db9a33734/asapdiscovery-docking/asapdiscovery/docking/docking.py#L286-L288
For instance, right now if you don't give POSIT any specifics we use the "ALL" method, and then the "ALL" method is saved in the SD tags. but it's actually more helpful if we record which sub-method was actually used (FRED / HYBRID / SHAPEFIT) etc.
=> Track the POSIT Method that was actually used during the docking

asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
Hotfix for a misspecified file hash.
=> hotfix testing hashes

asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
adds a quick post-simulation guardrail that sets ligand SMILES as names in case no names are set to ligands in an `alchemiscale` network.
=> quick guardrail that uses SMILES in case no names are set for ligands

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
this PR extends the ASAP-Alchemy status command with a flag to view the status of all networks in the users scope and provides a detailed breakdown of the status per network to help with #712.
=> ASAP-Alchemy: status all

asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_alchemy_prep.py
=> Remove oe version specific provenance testing

asapdiscovery-ml/asapdiscovery/ml/schema_v2/trainer.py
When the last batch is incomplete, `trainer()`should check if parameters have gradient before checking for NaN gradients.
Fix #804
=> fix trainer param gradient handling

asapdiscovery-ml/asapdiscovery/ml/asap_models.yaml, asapdiscovery-ml/asapdiscovery/ml/inference.py, asapdiscovery-ml/asapdiscovery/ml/models.py, asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py, devtools/conda-envs/asapdiscovery-macOS-latest.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
`mtenn` models will only work with certain versions of the package, so add pins in `asapdiscovery.ml.models.MLModelBase` to check and make sure versions are compatible. Fixes #532.
=> Add MTENN version check

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/prep.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
This PR improves the reporting of molecules which fail to have poses generated during `asap-alchemy prep run`. The molecules are saved to a csv file with their identifiers and information on why they might have failed rather than 2D molecules saved to an sdf. 
=> ASAP-Alchemy: Save failed pose generation molecules to csv

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/prep.py, asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py
This PR extends the ASAP-Alchemy prep CLI to take in postera molecule sets as input.
=> ASAP-Alchemy: Allow Postera molecule sets as input

asapdiscovery-data/asapdiscovery/data/dask_utils.py, asapdiscovery-data/asapdiscovery/data/tests/test_dask_clusters.py
FIxes #850 
Current theory is creating dask clusters in parallel is tripping over each other and interfering with other tests
=> Attempted hotfix of data CI

asapdiscovery-data/asapdiscovery/data/schema/identifiers.py, asapdiscovery-data/asapdiscovery/data/tests/test_ligand_schema.py
UUIDs cannot be serialised in Alchemy schema, so we should downcast to str
=> Cast UUIDs to str rather than UUID in identifiers

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py
Minor changes to the rdkit pose generation to improve reliability, we now remove the hydrogens from the reference compound when generating the alchemy poses. We can also now use the `dataset_name` from prep during the planning stage.
=> ASAP-Alchemy: Prep updates

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py, asapdiscovery-alchemy/asapdiscovery/alchemy/predict.py, asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_cli.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py
This PR extends the `asap-alchemy predict` CLI to optionally upload predictions to postera manifold. 
=> ASAP-Alchemy: Postera uploading

asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py, asapdiscovery-data/asapdiscovery/data/tests/postera/test_postera_live.py
enables pulling _all_ MoleculeSets at the same time without having to specify MoleculeSet names. @hmacdope any tests needed here?
=> drop in `pull_all()` after fixing imports

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-alchemy/asapdiscovery/alchemy/cli/prep.py, asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py
Solves https://github.com/choderalab/asapdiscovery/issues/896, makes sure that info messages aren't truncated and that we use more columns in the terminal to get less wrapping.
Makes CLI help printout look like:
```
$ asap-alchemy --help
Usage: asap-alchemy [OPTIONS] COMMAND [ARGS]...
Tools to create and execute Alchemy networks using OpenFE and alchemiscale.
Options:
--help  Show this message and exit.
Commands:
create   Create a new free energy perturbation factory with default settings and save it to JSON file.
prep     Tools to prepare ligands for Alchemy networks via state expansion and constrained pose generation.
plan     Plan a FreeEnergyCalculationNetwork using the given factory and inputs. The planned network will be written to file in a folder named after the
dataset.
submit …
```
=> Set order asap cli

.readthedocs.yaml
=> Fix  .readthedocs.yaml to install other packages

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/prep.py, asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py
This PR extends the CDD downloader utility to flag potential covalent ligands to ensure they are not used as references in the RBFE calculations. 
=> `ASAP-Alchemy`: Remove potential covalent ligands from CDD downloads

asapdiscovery-data/asapdiscovery/data/backend/openeye.py
Fixes #1000 
@apayne97  this was a subtle change in the `sdf_string_to_oemol` function such that it could now return `None` if no valid molecules were read. Related to #998, I am going to hotfix here, we can continue discussion about what the desired endstate should be there. 
The basic info though is that all of our `openeye` functions currently return an `OEMol` always, even if a read failed (making it the callee's responsibility to check if the OEMol is valid for their purpose.
If we change this so that the read will fail instead every call site has to check for success. This is doable and we can discuss.
=> hotfix subtle change to invariant in sdf_str function

asapdiscovery-cli/asapdiscovery/cli/cli_args.py, asapdiscovery-data/asapdiscovery/data/operators/selectors/selector.py, asapdiscovery-data/asapdiscovery/data/readers/meta_structure_factory.py, asapdiscovery-data/asapdiscovery/data/readers/structure_dir.py, asapdiscovery-data/asapdiscovery/data/services/fragalysis/fragalysis_reader.py, asapdiscovery-data/asapdiscovery/data/util/dask_utils.py, asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py, asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py, asapdiscovery-dataviz/asapdiscovery/dataviz/visualizer.py, asapdiscovery-docking/asapdiscovery/docking/docking.py, asapdiscovery-docking/asapdiscovery/docking/openeye.py, asapdiscovery-docking/asapdiscovery/docking/scorer.py, asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py, asapdiscovery-simulation/asapdiscovery/simulation/simulate.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/workflows.py, asapdiscovery-workflows/asapdiscovery/workflows/prep_workflows/cli.py
FIxes #1017 
Needs some wrangling around the `failure-mode` argument, but also fixes a few issues, including incorporating the changed in #997 (tagging @apayne97 ) which had a subtle interaction with the way dask backend handled array shaping, leading to #989
=> Add resilience to non-dask computation

asapdiscovery-ml/asapdiscovery/ml/models.py, devtools/conda-envs/asapdiscovery-macOS-12.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
I want to add MAFFT, the multi-sequence alignment tool I use for the genetics pipeline, to the .yml files since it can be installed via conda-forge now. 
=> Add MAFFT to the yaml installers

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py, asapdiscovery-data/asapdiscovery/data/backend/rdkit.py, asapdiscovery-data/asapdiscovery/data/schema/ligand.py, asapdiscovery-data/asapdiscovery/data/tests/conftest.py, asapdiscovery-data/asapdiscovery/data/tests/test_complex_schema.py, asapdiscovery-data/asapdiscovery/data/tests/test_ligand_schema.py, asapdiscovery-data/asapdiscovery/data/tests/test_selectors.py, asapdiscovery-data/asapdiscovery/data/tests/test_sets.py, asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py, asapdiscovery-docking/asapdiscovery/docking/tests/test_pose_generation.py, asapdiscovery-ml/asapdiscovery/ml/models.py
This PR adds a check to remove radical molecules from the cdd downloader in asap-alchemy to make sure such molecules are not used as experimental references in FEC networks. We also make sure ligands created from smiles have explicit hydrogens. 
=> `ASAP-Alchemy`: Catch radicals in CDD downloading

asapdiscovery-simulation/asapdiscovery/simulation/simulate.py, devtools/conda-envs/asapdiscovery-macOS-12.yml, devtools/conda-envs/asapdiscovery-macOS-latest.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
This PR exposed the small molecule OpenFF force field used in the `VanillaMDSimulator` as an option and updates the default to `openff-2.2.0.offxml` to take advantage of the improved sulfamide modelled geometries! 
=> `ASAP-Simulate`: update small molecule FF in `VanillaMDSimulator`

asapdiscovery-alchemy/asapdiscovery/alchemy/predict.py, asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py
@jthorton we should switch to pIC50 plotting by default. I know we want to have a toggled view between pIC50 and DG but this is a workable form for now, albeit not very elegantly written.
=> switch to pIC50 view in HTML reports

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/conftest.py, asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
This PR allows configuration of the alchemiscale `api_url` via the init or by setting the env variable `ALCHEMISCALE_URL` for the CLI allowing connection to other instances beyond the main deployment.  cc @JenkeScheen 
=> `ASAP-Alchemy`: Make the alchemiscale helper more flexible

asapdiscovery-ml/asapdiscovery/ml/cli.py, asapdiscovery-ml/asapdiscovery/ml/cli_args.py, asapdiscovery-ml/asapdiscovery/ml/trainer.py
Current training implementation saves a new weights file for each training epoch. This is nice for debugging but not for prod. This PR adds an option to `Trainer` (and to CLI) to control how often weights are saved. The new parameter is `Trainer.save_weights`, or `--save-weights` on the CLI. The options are:
* `"all"`: Keep every epoch's weight file (current behavior and will continue to be the default)
* `"recent"`: Only keeps the most recent epoch's weight file, saves it as `weights.th` in the output directory
* `"final"`: Only keep the final epoch, after the model has finished its entire training, saves as `final.th` (this file is included in both of the above options as well)
Note that if you select `"final"`, if your training job runs out of time or dies for any reason there will be …
=> Add option for adjusting weights saving frequency

asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py, asapdiscovery-alchemy/asapdiscovery/alchemy/tests/test_utils.py, asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py
solves https://github.com/asapdiscovery/asapdiscovery/issues/973
Instead of specifying during `submit`, there's now a separate CLI endpoint for adjusting network weights. users will be able to adjust network weights manually with minimal effort. We may need to revisit once we get _many_ networks running at the same time up to the point where manual adjustment is impractical, but with `alchemiscale`'s random actioning (influenced by weights) that may be complicated.
=> `ASAP-Alchemy` optimize prioritization

asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
The current implementation of `GIFVisualizer.visualize()` sometimes have issues with centering the final view of the output (which is a problem for the .gif file). I added the `zoom_view` parameter to `GIFVisualizer`, which if True, will center the .gif view to the binding site. 
I placed the centering command right before generating the _Session 6_ PyMOL output, so it only affect this and the .gif file. I could move it so it centers other outputs, but don't think it's important for a PyMOL file to be initially centered.
=> Add option to zoom GIFVisualizer into binding site

devtools/conda-envs/asapdiscovery-macOS-12.yml, devtools/conda-envs/asapdiscovery-macOS-latest.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
Going to cut an `mtenn` release soon that will break the current code, so pin to <= current version. Code is being updated to work with the new `mtenn` version in #1081.
=> Update mtenn pin for upcoming breaking release.

asapdiscovery-data/asapdiscovery/data/operators/selectors/mcs_selector.py, asapdiscovery-data/asapdiscovery/data/tests/test_selectors.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py, asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
Improves the MCS performance by allowing the use of a faster approximate method. 
We couldn't multiprocess or use dask due to limitations outlined in #560. 
We may need to investigate RDKit based MCS searching for a parallel component, but may run into the same issue there.
=> Improve MCS performance

asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
Adding option to do minimization to docking result without having to run equilibration/production. Fixes https://github.com/asapdiscovery/asapdiscovery/issues/1154 
=> Add minimize_only option to VanillaMDSimulator

asapdiscovery-data/asapdiscovery/data/readers/structure_dir.py, asapdiscovery-data/asapdiscovery/data/tests/test_structure_dir_factory_schema.py
Allows specifying a custom glob for `StructureDirFactory`
=> Add custom glob to structure dir

asapdiscovery-data/asapdiscovery/data/services/postera/molecule_set.py, asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py
Sometimes people put reserved keynames like `id` or `smiles` in customdata for a molecule, avoid this.
=> [HOTFIX] Fix edge case on clashing tag names in postera

asapdiscovery-alchemy/asapdiscovery/alchemy/predict.py, asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
This results in a 12-faced solvation box (fewer waters to simulate, i.e. faster production runs) and default filling to settings:
```
"solvation_settings": {
"solvent_model": "tip3p",
"solvent_padding": {
"magnitude": 1.2,
"unit": "nanometer",
":is_custom:": true,
"pint_unit_registry": "openff_units"
},
"box_shape": "dodecahedron",
"number_of_solvent_molecules": null,
"box_vectors": null,
"box_size": null
},
```
See OpenFE's docstring for this shape: https://github.com/OpenFreeEnergy/openfe/blob/35b5f12d2e948cc4c637177dd920f276e7f94259/openfe/protocols/openmm_utils/omm_settings.py#L121-L128
=> update default to much faster box shape

devtools/conda-envs/asapdiscovery-macOS-12.yml, devtools/conda-envs/asapdiscovery-macOS-latest.yml, devtools/conda-envs/asapdiscovery-ubuntu-latest.yml
`mtenn` was recently updated to pydantic 2, so pin the pydantic 1 version until `asapdiscovery` is updated. Closes #1244.
=> Pin mtenn version for pydantic 2

asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
1.2nm padding sometimes crashes in solvent phase - just switching back to 1.5 because solvent phase is fast anyway.
=> fix occasional crashes in solvent phase
